name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'code/Backend/**'
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/Backend
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Functions
        run: firebase deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
